apiVersion: apps/v1
kind: Deployment
metadata:
  name: varsha-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varsha-flask-app
  template:
    metadata:
      labels:
        app: varsha-flask-app
    spec:
      containers:
      - name: varsha-flask-app
        image: varsha-flask-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
